name: PartyChat
version: ${project.version}
main: lol.hyper.partychat.PartyChat
api-version: 1.16
authors: [hyperdefined]
description: Simple party chat.
commands:
  party:
    description: The main party command.
  pc:
    description: Send private party messages.